//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appartments
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Appartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appartment()
        {
            this.AppartmentFiles = new HashSet<AppartmentFile>();
        }
    
        public int IDAppartment { get; set; }

        [Required]
        [MaxLength(50, ErrorMessage = "Address must be at most 50 chars")]
        public string Address { get; set; }
        [Required]
        [MaxLength(20, ErrorMessage = "City must be at most 20 chars")]
        public string City { get; set; }
        [Required]
        public int AgentID { get; set; }
    
        public virtual Agent Agent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppartmentFile> AppartmentFiles { get; set; }
    }
}
