//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appartments
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppartmentFile
    {
        public int IDAppartmentFile { get; set; }
        public string Name { get; set; }
        public string ContentType { get; set; }
        public byte[] Content { get; set; }
        public int AppartmentID { get; set; }
    
        public virtual Appartment Appartment { get; set; }
    }
}
